name: "trusted-publishing"
author: "WIP"
description: "Retrieve a temporary access token for trusted publishing with crates.io."
inputs:
  endpoint:
    description: "cargo registry endpoint, defaults to crates.io"
    required: false
    default: "https://crates.io"
    type: string
outputs:
  token:
    description: "The temporary access token you can use to login with cargo"
    value: ${{ steps.request.outputs.token }}
branding:
  icon: "zap"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - name: Retrieve trusted publishing token
      id: request
      shell: bash
      run: |
        # Send the request to the endpoint to retrieve the token.
        response=$(curl -X PUT ${{ inputs.endpoint }}/api/v1/trusted_publishing/tokens)

        # Extract the token from the JSON response `{ "token": "string" }`.
        token=$(echo "$response" | jq -r '.token')

        # Store the token in GitHub Actions output
        echo "token=$token" >> $GITHUB_OUTPUT
