name: "trusted-publishing"
author: "WIP"
description: "Retrieve a temporary access token for trusted publishing with crates.io."
inputs:
  url:
    description: "cargo registry url, defaults to crates.io"
    required: false
    default: "https://crates.io"
    type: string
outputs:
  token:
    description: "The temporary access token you can use to login with cargo"
    value: ${{ steps.request.outputs.token }}
branding:
  icon: "zap"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - name: Retrieve trusted publishing token
      id: request
      shell: bash
      env:
        REGISTRY_URL: ${{ inputs.url }}
      run: |
        "${{ github.action_path }}/script.sh"
