name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

permissions: {}

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Prettier
        run: npm ci

      - name: Format
        run: npx prettier --check .
