name: Test

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start mock crates.io server
        run: |
          # Build the mock server before running it so that
          # `cargo run` finds the binary and we can run it in the background
          cargo build --manifest-path=mock/Cargo.toml
          cargo run --manifest-path=mock/Cargo.toml &

          # Wait for server to be ready
          retry_count=0
          max_retries=3
          until curl -s http://localhost:3000/health > /dev/null 2>&1; do
            echo "Waiting for mock server to start... (attempt $((retry_count + 1))/$max_retries)"
            sleep 2
            retry_count=$((retry_count + 1))
            if [ $retry_count -ge $max_retries ]; then
              echo "Mock server failed to start after $max_retries attempts"
              exit 1
            fi
          done
          echo "Mock server is ready"
      - name: Run trusted publishing action
        id: trusted-publishing
        uses: ./ # Uses the action in the root directory
        with:
          endpoint: "http://localhost:3000" # Mock server endpoint
      - name: Assert output
        env:
          TOKEN: ${{ steps.trusted-publishing.outputs.token }}
        run: |
          if [ "$TOKEN" != "mock-token" ]; then
            echo "Expected token to be 'mock-token', but got '$TOKEN'"
            exit 1
          fi
          echo "Token assertion passed. Token value: $TOKEN"
